### ISSUE TITLE
Deployment stage not working

### ISSUE THREAD

**Issue by tinchom** [awslabs/aws-greengrass-labs-component-for-home-assistant#16]
Hi, i am following the step by step but in deployment phase something is wrong. I made two path: automatic and manual.
I am using EC2 instance with ubuntu 22.04

**Automatic**
bash quickstart.sh Greengrass-EC2

Have you added the bucket and secret permissions to the Greengrass device role? ('Press 'y' for yes or 'x' to exit)

---------- Deploy the new Greengrass component version ----------
Getting the Home Assistant secret greengrass-home-assistant
Attempting deployment of version 1.0.0 to core device Greengrass-EC2
Searching for existing single Thing deployment for Greengrass-EC2
No existing Thing deployment for this Core Device. Abort.

**Manual/Slow start**
Its ok and up/running until point 12 of the step by step. the command gdk component publish worked. The problem is with the command: python3 deploy_component_version.py 1.0.0 Greengrass-EC2
Getting the Home Assistant secret greengrass-home-assistant
Attempting deployment of version 1.0.0 to core device Greengrass-EC2
Searching for existing single Thing deployment for Greengrass-EC2
No existing Thing deployment for this Core Device. Abort.

Working directly with aws portal for deployment state i also get failed result.
More information about this scenario: i have two policies at aws greengrass created: [GreengrassV2TokenExchangeRoleAccess and 
MyGreengrassV2ComponentArtifactPolicy. both are attached to entity GreengrassV2TokenExchangeRole

GreengrassV2TokenExchangeRoleAccess:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iot:DescribeCertificate",
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "logs:DescribeLogStreams",
                "s3:GetBucketLocation"
            ],
            "Resource": "*"
        }
    ]
}

MyGreengrassV2ComponentArtifactPolicy:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": "arn:aws:s3:::greengrass-home-assistant-us-east-1-ID/*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "secretsmanager:GetSecretValue"
            ],
            "Resource": "arn:aws:secretsmanager:us-east-1:ID:secret:greengrass-home-assistant-gJkWoP"
        }
    ]
}

Let me know if i miss something.

Thanks,
Martin

**Comment by gregbreen** [comment]
Both approaches call the `deploy_component_version.py` script and, in both cases, it fails with this:

> No existing Thing deployment for this Core Device. Abort.

With Greengrass, you can create deployments that target a single Thing or a Thing Group: https://docs.aws.amazon.com/greengrass/v2/developerguide/create-deployments.html. In your case, your deployment must be targeting a Thing group. The script looks for an existing single Thing deployment for the Thing name passed in the 3rd argument. It isn't finding one in your case.

At present, the component is only expecting to be deployed to one Thing, not a group. Simply because I haven't done anything to pluralize the configuration (including the secret). So you can't have unique configuration for each device in a group. Such capability could be developed, but this example doesn't go that far.

So you didn't do anything wrong; my documentation just isn't good enough. Probably the easiest path forward is to create a single Thing deployment for the device, and then run my scripts again.

**Comment by tinchom** [comment]
I found the solution to keep going:
Fix is to create the core device from Aws greengrass without group.

Thanks!
